default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: care4luggage_development

test: &test
  <<: *default
  database: care4luggage_test

production:
  <<: *default
  database: care4luggage_production

cucumber:
  <<: *test